GoalsApp/config/routes.rb
GoalsApp::Application.routes.draw do

  resources :users
  resource :session
  resources :goals do
    resources :cheers, :only => [:create, :destroy]
  end
<<<<<<< HEAD
  resources :categories
  root :to => "categories#index"
=======

  root :to => "sessions#new"
>>>>>>> parent of 1a294b5... Adds awesome styling and cheers/leaderboards
end

GoalsApp/app/models/cheer.rb
class Cheer < ActiveRecord::Base
  attr_accessible :goal_id, :user_id
  validate :user_cheer_counts

  belongs_to :user
  belongs_to :goal

  private

  def user_cheer_counts
    errors.add(:cheer, "No more cheers :( ") if self.user.cheers.count > 9
  end

end

GoalsApp/app/models/goal.rb
class Goal < ActiveRecord::Base
  attr_accessible :body, :completed, :title, :user_id, :private

  validates :title, :user_id, :presence => true


  belongs_to :user
  has_many :cheers

end

GoalsApp/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :password
  before_validation :reset_session_token
  validates :username, :password_digest, :session_token, :presence => true

  has_many :goals
  has_many :cheers

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    return user if user && user.is_password?(password)
    nil
  end

  def generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def is_password?(pass)
    BCrypt::Password.new(self.password_digest).is_password?(pass)
  end

  def password=(pass)
    self.password_digest = BCrypt::Password.create(pass)
  end

  def reset_session_token
    self.session_token = generate_session_token
  end

  def reset_session_token!
    reset_session_token
    self.save!
  end

end

GoalsApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

GoalsApp/app/controllers/cheers_controller.rb
class CheersController < ApplicationController
  def create
    @cheer = Cheer.new
    @cheer.user_id = current_user.id
    @cheer.goal_id = params[:goal_id]
    flash[:errors] = @cheer.errors.full_messages unless @cheer.save
    redirect_to goal_url(@cheer.goal)
  end

  def destroy
  end
end

GoalsApp/app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def create
    @goal = Goal.new(params[:goal])
    @goal.user = current_user
    flash[:errors] = @goal.errors.full_messages unless @goal.save
    redirect_to user_url(@goal.user)
  end

  def new
  end

  def destroy
  end

  def show
    @goal = Goal.find(params[:id])
  end

  def update
    @goal = Goal.find(params[:id])
    if @goal.update_attributes(params[:goal])
      redirect_to goal_url(@goal)
    else
      flash[:errors] = @goal.errors.full_messages
      render :edit
    end
  end

  def edit
    @goal = Goal.find(params[:id])
  end

  def index
  end
end

GoalsApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.find_by_credentials(*params[:user].values)
    if @user
      login!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:messages] = ["Invalid username or password"]
      render :new
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end

end

GoalsApp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new(params[:user])
    if @user.save
      login!(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def destroy
  end

  def new
    # @user = User.new
    render :new
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @goals = @user.goals
    @goal = Goal.new
    @private_goals = @goals.select { |goal| goal.private }
    @public_goals = @goals.select { |goal| !goal.private }
  end

  def edit
  end

  def update
  end
end

GoalsApp/app/helpers/application_helper.rb
module ApplicationHelper
end

GoalsApp/app/helpers/cheers_helper.rb
module CheersHelper
end

GoalsApp/app/helpers/goals_helper.rb
module GoalsHelper
end

GoalsApp/app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def login!(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

end

GoalsApp/app/helpers/users_helper.rb
module UsersHelper
end

GoalsApp/app/views/cheers/create.html.erb
<h1>Cheers#create</h1>
<p>Find me in app/views/cheers/create.html.erb</p>

GoalsApp/app/views/cheers/destroy.html.erb
<h1>Cheers#destroy</h1>
<p>Find me in app/views/cheers/destroy.html.erb</p>

GoalsApp/app/views/goals/_goal_form.html.erb
<% if @goal.id %>
	<h3>Edit Goal</h3>
	<% submit_value = "Edit goal" %>
<% else %>
	<h3>Create Goal</h3>
	<% submit_value = "Create goal" %>
<% end %>

<% if @goal.id %>
<form action="<%= goal_url(@goal) %>" method="POST">
<input type="hidden" name="_method" value="put">
<% else %>
<form action="<%= goals_url %>" method="POST">
<% end %>

	<input type="hidden"
	name="authenticity_token"
	value="<%= form_authenticity_token %>">

	<label for="title">Title</label>
	<input type="text" name="goal[title]" id="title" value="<%= @goal.title %>">
<br>
	<label for="body">Body</label>
<br>
	<textarea id="body" name="goal[body]"><%= @goal.body %></textarea>
<br>
	<input type="radio" id="private" name="goal[private]" value="true">
	<label for="private">Private</label>
<br>
	<input type="radio" id="public" name="goal[private]" value="false">
	<label for="public">Public</label>
<br>
	<label for="completed">Completed?</label>
	<input type="hidden" name="goal[completed]" value="false">
	<input type="checkbox" id="completed" name="goal[completed]" value="true">
<br>
	<input type="submit" value="<%= submit_value %>">

</form>

GoalsApp/app/views/goals/create.html.erb
<h1>Goals#create</h1>
<p>Find me in app/views/goals/create.html.erb</p>

GoalsApp/app/views/goals/destroy.html.erb
<h1>Goals#destroy</h1>
<p>Find me in app/views/goals/destroy.html.erb</p>

GoalsApp/app/views/goals/edit.html.erb
<%= render 'goal_form' %>

GoalsApp/app/views/goals/index.html.erb
<h1>Goals#index</h1>
<p>Find me in app/views/goals/index.html.erb</p>

GoalsApp/app/views/goals/new.html.erb
<h1>Goals#new</h1>
<p>Find me in app/views/goals/new.html.erb</p>

GoalsApp/app/views/goals/show.html.erb
<h1>Goal: <%= @goal.title%></h1>
<%= @goal.body %><br>
Private? <%= @goal.private %><br>
Completed? <%= @goal.completed %>
Cheers: <%= @goal.cheers.count %>
<%= button_to("Cheer this goal", goal_cheers_url(@goal), :method => "POST") %>
<br>
<%= link_to("Return to profile", user_url(@goal.user)) %>
<%= link_to("Edit goal", edit_goal_url(@goal)) %>

GoalsApp/app/views/goals/update.html.erb
<h1>Goals#update</h1>
<p>Find me in app/views/goals/update.html.erb</p>

GoalsApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoalsApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<<<<<<< HEAD
	<div id="header">
	<h1><%= link_to("Goals App", root_url %></h1>
	</div>
=======
>>>>>>> parent of 1a294b5... Adds awesome styling and cheers/leaderboards

	<% if flash[:errors] && !flash[:errors].empty? %>
		<%= flash[:errors] %>
		<%end%>


<% if current_user %>
	<%= current_user.username %>
	<%= button_to("Sign Out", session_url, method: "delete") %>
<% else %>
	<%= link_to("Sign In", new_session_url) %>
	<%= link_to("Sign Up", new_user_url )%>
<% end %>

<%= yield %>



</body>
</html>

GoalsApp/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

GoalsApp/app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

GoalsApp/app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

GoalsApp/app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

GoalsApp/app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="POST" >

	<input type="hidden"
					name="authenticity_token"
					value="<%= form_authenticity_token %>">

	<label for="username">Username</label>
	<input type="text" name="user[username]" id="username">

	<label for="password">Password</label>
	<input type="password" name="user[password]" id="password">

	<input type="submit" value="Create new user!">

				</form>

GoalsApp/app/views/users/show.html.erb
<h1><%= @user.username %>'s page</h1>

<% if current_user == @user %>
	<%= render 'goals/goal_form' %>
	<h2>Private goals</h2>
	<ul>
		<% @private_goals.each do |private_goal| %>
		<li> <%= link_to(private_goal.title, goal_url(private_goal)) %>
			<%= link_to("Edit goal", edit_goal_url(private_goal))%> </li>
		<% end %>
	</ul>

<% end %>

<h2>Public goals</h2>
<ul>
	<% @public_goals.each do |public_goal| %>
	<li>
		<%= link_to(public_goal.title, goal_url(public_goal)) %><br>
		<%= link_to("Edit goal", edit_goal_url(public_goal))%>
	</li>
	<% end %>
</ul>

GoalsApp/app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>